"""Initial schema creation

Revision ID: 6954f76c47c2
Revises: None
Create Date: 2025-10-05 13:36:14.000208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '6954f76c47c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('profile_icon', sa.String(length=30), nullable=True),
    sa.Column('password', sa.VARBINARY(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('third_party_auth_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_user')
    )
    op.create_index('idx_provider', 'third_party_auth_users', ['provider'], unique=False)
    op.create_index('idx_user_id', 'third_party_auth_users', ['user_id'], unique=False)
    op.create_table('user_cookies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cookie', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cookie')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=30), nullable=False),
    sa.Column('file_dir', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('third_party_auth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('third_party_auth_user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=500), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('auth_metadata', sa.JSON(), nullable=False),
    sa.Column('one_time_token', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['third_party_auth_user_id'], ['third_party_auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('third_party_auth_tokens')
    op.drop_table('comments')
    op.drop_table('videos')
    op.drop_table('user_cookies')
    op.drop_index('idx_user_id', table_name='third_party_auth_users')
    op.drop_index('idx_provider', table_name='third_party_auth_users')
    op.drop_table('third_party_auth_users')
    op.drop_table('users')
    # ### end Alembic commands ###
    # ### end Alembic commands ###