steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/server-dev:1.0.0'
  - '-f'
  - '../cloud/Docker/server/server.Dockerfile'
  - '.'
images:
- 'gcr.io/$PROJECT_ID/server-dev:1.0.0'
